dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer config --global --auth gitlab-token.gitlab.com uZXkekz-AfYfR-P3UcjG

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --verbose
